### ISSUE TITLE
QA and Programmers: create wireframes

### ISSUE THREAD

**Issue by benator** [takchiks/ratemylab#29]

**Comment by tvrjuana** [comment]
[WireFrames_Sprint_1_Part_2.pdf](https://github.com/takchiks/ratemylab/files/5337163/WireFrames_Sprint_1_Part_2.pdf)




Wireframes for New Lab, Select Students, and Student

**Comment by tvrjuana** [comment]
[WireFrames_Sprint_1_Part_1.pdf](https://github.com/takchiks/ratemylab/files/5337295/WireFrames_Sprint_1_Part_1.pdf)

From Safwan:
Wireframes for Homepage, Previous Lab, Lab Difficulty

**Comment by SafwanA12** [comment]
Re did my wireframes

**Comment by SafwanA12** [comment]
[wireframe1-3.pdf](https://github.com/takchiks/ratemylab/files/5342333/wireframe1-3.pdf)
