### ISSUE TITLE
Connect to Databse

### ISSUE THREAD

**Issue by benator** [takchiks/ratemylab#30]
after we get password reset info from the department folks

**Comment by tvrjuana** [comment]
Connecting to the server 
![Screenshot (17)](https://user-images.githubusercontent.com/47215199/95405528-11db0a00-08e6-11eb-9265-eaee709f0892.png)
![Screenshot (19)](https://user-images.githubusercontent.com/47215199/95405733-9594f680-08e6-11eb-98ee-d320b353da24.png)
