### ISSUE TITLE
WireFraming for Sprint 2

### ISSUE THREAD

**Issue by SafwanA12** [takchiks/ratemylab#38]
There are some adjustments and things we will have to change on our frames based on our last meeting with the professor(3 "new" pages). We will need to adjust and repost new wireframes and build the actual code based on that. I have attached the below notes from that meeting. Please try to get this part done first as we cannot move on without it. (If you have questions try to contact the pm's Juana or Jordan)![Screen Shot 2020-10-19 at 12.57.34 PM.png](https://images.zenhubusercontent.com/5f7bd2d1af8f03d66c8e69e8/190d30f4-711a-4157-b0cc-0e551172793c)

**Comment by almorrison** [comment]
Tentative edited wireframes

![WireFrames_Sprint_2_Part_1.png](https://images.zenhubusercontent.com/5f590f17c98fd5fd340dfc55/2851a6cb-578b-444b-834e-cd236e019d39)

![WireFrames_Sprint_2_Part_2.png](https://images.zenhubusercontent.com/5f590f17c98fd5fd340dfc55/b6e08924-f6fc-4185-9a84-9f48dfc2b200)
