### ISSUE TITLE
Research and Discovery

### ISSUE THREAD

**Issue by benator** [takchiks/ratemylab#4]
"As R&D is gathered, submit a small one paragraph report of the task into GitHub" -Sprint1 Preparation Checklist

**Comment by tvrjuana** [comment]
[Student Affect in CS1.pdf](https://github.com/takchiks/ratemylab/files/5343900/Student.Affect.in.CS1.pdf)
Summarizes the paper and how it can be relevant to the project.

**Comment by almorrison** [comment]
[pdf detailing node.js / MySQL research](https://app.zenhub.com/files/295429935/034aeb56-d6cd-4567-a481-27637ee275d0/download)
