### ISSUE TITLE
Diagrams for Sprint 2

### ISSUE THREAD

**Issue by SafwanA12** [takchiks/ratemylab#45]
This epic will include the case and sequence diagrams for this project

**Comment by tvrjuana** [comment]
Use case diagram for landing page. Only one actor
![CaseDiagramLP](https://user-images.githubusercontent.com/47215199/97491481-9a265b00-1938-11eb-9d47-10fd58ad1e3d.PNG)

**Comment by tvrjuana** [comment]
Updated use case diagram for landing page.
![image](https://user-images.githubusercontent.com/47215199/97509971-10878500-195a-11eb-9237-0fc1afe2f86a.png)

**Comment by tvrjuana** [comment]
Use case diagram for change password. Only one actor.
![CaseDiagramCPW](https://user-images.githubusercontent.com/47215199/97511024-6fe69480-195c-11eb-9af3-d137195364ae.PNG)

**Comment by tvrjuana** [comment]
Use case diagram for CRN. Two actors.
![image](https://user-images.githubusercontent.com/47215199/97513101-b1c60980-1961-11eb-92c8-ad7c5f43bc52.png)

**Comment by tvrjuana** [comment]
Use case diagram for selected labs. Two actors.
![image](https://user-images.githubusercontent.com/47215199/97515772-2734d880-1968-11eb-8556-88fdccb8b75a.png)
