### ISSUE TITLE
UML Diagram for Landing Page

### ISSUE THREAD

**Issue by SafwanA12** [takchiks/ratemylab#46]
This diagram can be made referencing the wireframe for the landing page.

**Comment by tvrjuana** [comment]
Use case diagram for landing page only has 1 actor.
![CaseDiagramLP](https://user-images.githubusercontent.com/47215199/97490272-01dba680-1937-11eb-893e-f10a337852b5.PNG)

**Comment by tvrjuana** [comment]
An updated use case diagram for landing page/login page

![image](https://user-images.githubusercontent.com/47215199/97511556-ba1c4580-195d-11eb-85b2-f3968adcc54e.png)
